In [2]:
import numpy as np

In [4]:
a = np.arange(6)

In [5]:
type(a)

numpy.ndarray

In [6]:
a

array([0, 1, 2, 3, 4, 5])

In [7]:
a2 = a[np.newaxis, :]

In [8]:
a2.shape

(1, 6)

In [9]:
a

array([0, 1, 2, 3, 4, 5])

In [10]:
a = np.array([1, 2, 3, 4, 5, 6])

In [11]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [12]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
a[0,1]

2

In [14]:
a[2]

array([ 9, 10, 11, 12])

In [15]:
a = np.array([1, 2, 3])

In [16]:
np.zeros(2)

array([0., 0.])

In [17]:
np.ones(2)

array([1., 1.])

In [18]:
np.empty(2) 

array([1., 1.])

In [19]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [20]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
x = np.ones(2, dtype=np.int64)

In [23]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [24]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
a

array([1, 2, 3])

In [26]:
np.lexsort(arr)

0

In [29]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [31]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
x = np.array([[1, 2], [3, 4]])

In [33]:
y = np.array([[5, 6]])

In [34]:
x

array([[1, 2],
       [3, 4]])

In [35]:
y

array([[5, 6]])

In [40]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [3]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [4]:
array_example.ndim

3

In [5]:
array_example.size

24

In [6]:
array_example.shape

(3, 2, 4)

In [17]:
a = np.arange(6)

In [18]:
print(a)

[0 1 2 3 4 5]


In [20]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [21]:
a

array([0, 1, 2, 3, 4, 5])

In [23]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [24]:
col_vector = a[:, np.newaxis]

In [25]:
col_vector.shape

(6, 1)

In [28]:
a = a[:, np.newaxis]

In [29]:
a

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [30]:
a = a[np.newaxis, :]

In [31]:
a

array([[[0],
        [1],
        [2],
        [3],
        [4],
        [5]]])

In [32]:
a = np.array([1, 2, 3, 4, 5, 6])

In [33]:
a.shape

(6,)

In [34]:
b = np.expand_dims(a, axis=1)

In [35]:
b.shape

(6, 1)

In [36]:
c = np.expand_dims(a, axis=0)

In [37]:
c.shape

(1, 6)

In [38]:
data = np.array([1, 2, 3])

In [39]:
data[1]

2

In [40]:
data[0:2]

array([1, 2])

In [41]:
data[1:]

array([2, 3])

In [43]:
data[-2]

2

In [44]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [49]:
print(a[a > 5])

[ 6  7  8  9 10 11 12]


In [50]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [51]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [52]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [53]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [54]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [55]:
b = np.nonzero(a < 5)

In [56]:
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [57]:
list_of_coordinates= list(zip(b[0], b[1]))

In [58]:
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [59]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [60]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [62]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

In [63]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [64]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [65]:
x = np.arange(1, 25).reshape(2, 12)

In [66]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [67]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [68]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [74]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [71]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [72]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [73]:
b2 = a.copy()

In [76]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [77]:
ones

array([1, 1])

In [78]:
data - ones

array([0, 1])

In [79]:
data * data

array([1, 4])

In [80]:
data / data

array([1., 1.])

In [81]:
a = np.array([1, 2, 3, 4])

In [82]:
a.sum()

10

In [83]:
b = np.array([[1, 1], [2, 2]])

In [84]:
b.sum(axis=0)

array([3, 3])

In [85]:
b.sum(axis=1)

array([2, 4])

In [86]:
data = np.array([1.0, 2.0])

In [87]:
data * 1.6

array([1.6, 3.2])

In [88]:
data.max()

2.0

In [89]:
data

array([1., 2.])

In [90]:
data.min()

1.0

In [91]:
data.sum()

3.0

In [92]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [93]:
a.sum()

4.8595784

In [94]:
a.min()

0.05093587

In [99]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [96]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [97]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [100]:
data[0, 1]

2

In [103]:
data[1, 1]

4

In [104]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [105]:
data[0:2, 0]

array([1, 3])

In [106]:
data.max()

6

In [107]:
data.min()

1

In [108]:
data.sum()

21

In [109]:
data = np.array([[1, 2], [5, 3], [4, 6]])

In [110]:
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [111]:
data.max(axis=0)

array([5, 6])

In [112]:
data.max(axis=1)

array([2, 5, 6])

In [113]:
data = np.array([[1, 2], [3, 4]])

In [129]:
ones = np.array([[1, 1], [1, 1]])

In [125]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [126]:
ones_row = np.array([[2, 2]])

In [127]:
data + ones_row

array([[3, 4],
       [5, 6],
       [7, 8]])

In [128]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [131]:
np.zeros(3)

array([0., 0., 0.])

In [132]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [137]:
rng = np.random.default_rng()

In [138]:
rng.random((3, 2)) 

array([[0.11078783, 0.86076944],
       [0.11621814, 0.71296936],
       [0.92669341, 0.79465014]])

In [139]:
rng.integers(5, size=(2, 4)) 

array([[4, 2, 2, 1],
       [3, 3, 2, 4]], dtype=int64)

In [140]:
rng.integers(5, size=(2, 4)) 

array([[4, 2, 3, 1],
       [1, 2, 0, 0]], dtype=int64)

In [141]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [142]:
unique_values = np.unique(a)

In [143]:
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [144]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [145]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [146]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])


In [147]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [148]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [150]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)


In [151]:
print(unique_rows)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [152]:
print(indices)


[0 1 2]


In [153]:
print(occurrence_count)


[2 1 1]


In [154]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [155]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [156]:
arr = np.arange(6).reshape((2, 3))

In [157]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [158]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [159]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [160]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [161]:
reversed_arr = np.flip(arr)

In [162]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [163]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [164]:
reversed_arr = np.flip(arr_2d)

In [165]:
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [166]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [167]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [168]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [169]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [170]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [171]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [172]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [173]:
print(a1)  # New array

[99  2  3  4  5  6  7  8  9 10 11 12]


In [174]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [175]:
print(a2)  # New array

[98  2  3  4  5  6  7  8  9 10 11 12]
